export const rPool_data=[{
  text:"Staker",
  url:"/rKSM/staker/index",
  child:[
    {
      text:'-Status',
      url:"/rKSM/staker/info"
    },
    {
      text:'-Reward',
      url:"/rKSM/staker/reward"
    },
    {
      text:'-Recovery',
      url:"/rKSM/search"
    }
  ]
},{
  text:"Validator",
  url:"/rKSM/validator", 
}]